services:
  proxy:
    build:
      context: ./nginx
    depends_on:
      - backend_core
    ports:
      - 8042:80
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - backend_core_network
  backend_core:
    build:
      context: ./backend_core
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./backend_core/env/.env
    depends_on:
      - backend_core_db
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - backend_core_network
      - backend_db_network
    volumes:
      - static_volume:/app/staticfiles
  backend_core_db:
    image: postgres:14-alpine
    volumes:
      - backend_core_db_volume:/var/lib/postgresql/data
    env_file:
      - ./backend_core/env/.env
    ports:
      - 5432:5432
    networks:
      - backend_db_network

volumes:
  backend_core_db_volume:
  static_volume:

networks:
  backend_core_network:
    driver: bridge
  backend_db_network:
    driver: bridge